import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Speechmatics Flow example',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-1 flex-col h-screen`}>
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}